### ISSUE TITLE
Update git-pr-release to v1.6.0

### ISSUE THREAD

**Issue by katoken-0215** [bakunyo/git-pr-release-action#12]
Hi @bakunyo ,

https://github.com/x-motemen/git-pr-release v1.6.0 is released including several fix 5 days ago, but `git-pr-release-action@master` seems not including this updated version.

Would you update it ?

**Comment by bakunyo** [comment]
Thank you for your interest @katoken-0215 .
`git-pr-release-action` [install latest version of git-pr-release](https://github.com/bakunyo/git-pr-release-action/blob/dfee697ee30876e5f710ae9159429178ad27599c/Dockerfile#L5), so now use v1.6.0 automatically.

![image](https://user-images.githubusercontent.com/2487437/119228378-b8121200-bb4d-11eb-9ff7-1d3a5f8d2039.png)

**Comment by katoken-0215** [comment]
@bakunyo Thank you so much!
